// Scaffold output — regenerated by scripts/scaffold.sh; do not hand-edit.
// Custom logic belongs in a separate partial-class file.
namespace ProjectManagementSystem.Data.Entities;

public partial class User
{
    public Guid Id { get; set; }
    public string Username { get; set; } = null!;
    public string PasswordHash { get; set; } = null!;
    public string Role { get; set; } = null!;
    public DateTime CreatedAt { get; set; }
}
